USE BDInkasFerro_Almudena
GO

DECLARE @SUCUR_Id INT = 2
DECLARE @ZONAS_Codigo CHAR(5) = '54.00'

INSERT INTO dbo.Parametros
        ( PARMT_Id ,             APLIC_Codigo ,          ZONAS_Codigo ,          SUCUR_Id ,
          PARMT_Valor ,          PARMT_Descripcion ,     PARMT_TipoDato ,        PARMT_General)
   SELECT PARMT_Id ,             APLIC_Codigo ,          ZONAS_Codigo ,          SUCUR_Id ,
          PARMT_Valor ,          PARMT_Descripcion ,     PARMT_TipoDato ,        PARMT_General
    FROM (SELECT PARMT_Id = 'Empresa', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '20490262181' , PARMT_Descripcion = 'Codigo de la Empresa', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'EmpresaRS', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = 'INVERSIONES INKASFERRO SRL' , PARMT_Descripcion = 'Nombre Comercial', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'ListaPrecioDefa', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '2' , PARMT_Descripcion = 'Lista de Precios por Defecto', PARMT_TipoDato = 'Long', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_BloqueoMND', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Bloquear el campo moneda', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_BusqAutoma', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Busqueda en automatico para entidades/clientes', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_BusqEntAll', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Busqueda de Todas las Entidades', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_CamFechFactu', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Permitir cambiar la fecha en la facturacion', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_CargaMax', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '42500' , PARMT_Descripcion = 'Carga Maxima para las Guias de Remision', PARMT_TipoDato = 'Decimal', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_CargaMax', APLIC_Codigo = 'vta', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '430000' , PARMT_Descripcion = 'Carga Maxima para las Guias de Remision', PARMT_TipoDato = 'Decimal', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_ChangeColor', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Cambiar el Color por la Configuracion definida ', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_ColorBack', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '211,211,211' , PARMT_Descripcion = 'Color de Fondo', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_ColorDegred', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '186,176,177' , PARMT_Descripcion = 'Color Degrade', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_ColorTitle', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '57,51,51' , PARMT_Descripcion = 'Color de Titulo', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_CondXVehi', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Conductores por Vehiculo', PARMT_TipoDato = 'Integer', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_CondXVehi', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Conductores por Vehiculo', PARMT_TipoDato = 'Integer', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_CotizNuevo', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Cargar la cotizacion para Ingresar un registro', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_DesCarPrec', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Desactiva mostrar los precios al entrar ', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_FacDetCtaCte', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'Cta. Cte. Bco de la Nación 101-091929' , PARMT_Descripcion = 'Cuenta de Banco', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_Facturar', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '0' , PARMT_Descripcion = 'Definir la operacion de Facturar Pedido', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_FecIniFletes', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '02-03-2012' , PARMT_Descripcion = 'Fecha de Inicio de Fletes por Facturar', PARMT_TipoDato = 'DateTime', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_FFechaHora', APLIC_Codigo = 'LOG', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'dd/MM/yyyy hh:mm tt' , PARMT_Descripcion = 'Formato de Fecha Hora', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_FFechaHora', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'dd/MM/yyyy hh:mm tt' , PARMT_Descripcion = 'Formato de Fecha Hora', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_FFechaHora', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'dd/MM/yyyy hh:mm tt' , PARMT_Descripcion = 'Formato de Fecha Hora', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_FMondo2d', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '#,###,##0.00' , PARMT_Descripcion = 'Formato de Moneda 2 decimales', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_FMondo3d', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '#,###,##0.000' , PARMT_Descripcion = 'Formato de Moneda 3 Decimales', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_FMondo4d', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '#,###,##0.0000' , PARMT_Descripcion = 'Formato de Moneda 4 Decimales', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_FormatoFecha', APLIC_Codigo = 'LOG', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'dd/MM/yyy' , PARMT_Descripcion = 'Formato Fecha', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_FormatoFecha', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'dd/MM/yyy' , PARMT_Descripcion = 'Formato Fecha', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_FormatoFecha', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'dd/MM/yyy' , PARMT_Descripcion = 'Formato Fecha', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_ImpDefault', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '\\Scc-hp\epson lx-350 facturas' , PARMT_Descripcion = 'Impresora por Defecto', PARMT_TipoDato = 'String', PARMT_General = 0
    UNION SELECT PARMT_Id = 'pg_ImpOrden', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '\\Scc-hp\epson lx-350 facturas' , PARMT_Descripcion = 'Impresora para Ordenes de Recojo', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_LimitDoc', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '700' , PARMT_Descripcion = 'Precio minimo permitido para datos del comprador', PARMT_TipoDato = 'System.Decimal', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_LimitRedonde', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Limite de importe para ser redondeado', PARMT_TipoDato = 'Decimal', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_LongTexAyuda', APLIC_Codigo = 'DIS', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '3' , PARMT_Descripcion = 'Longitud para activar la ayuda de las busquedas', PARMT_TipoDato = 'Integer', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_LongTexAyuda', APLIC_Codigo = 'LOG', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '3' , PARMT_Descripcion = 'Longitud para activar la ayuda de las busquedas', PARMT_TipoDato = 'Integer', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_LongTexAyuda', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Longitud para activar la ayuda de las busquedas', PARMT_TipoDato = 'Integer', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_LongTexAyuda', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '2' , PARMT_Descripcion = 'Longitud para activar la ayuda de las busquedas', PARMT_TipoDato = 'Integer', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_NeumaMoneda', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'MND002' , PARMT_Descripcion = 'Moneda para el precio de los neumaticos', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_NeumaMoneda', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'MND002' , PARMT_Descripcion = 'Moneda para el precio de los neumaticos', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_NotCredCuot', APLIC_Codigo = 'LOG', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'CPD07' , PARMT_Descripcion = 'Codigo de la nota de credito para el control de cu', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_ocultarGrafi', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Ocultar los graficos de Neumaticos', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_ocultarGrafi', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Ocultar los graficos de Neumaticos', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_PercBolCant1', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Sin percepción para boletas con 1 solo item y 1 pr', PARMT_TipoDato = 'Decimal', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_PercNormal', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '2' , PARMT_Descripcion = 'Percepción Normal de Un Cliente', PARMT_TipoDato = 'Decimal', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_PerStockNega', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = NULL, PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_PreLimBoleta', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1500' , PARMT_Descripcion = 'LIMITE', PARMT_TipoDato = 'Decimal', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_PreLimBoleta', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1500' , PARMT_Descripcion = 'Precio minimo permitido sin percepcion en boletas', PARMT_TipoDato = 'Decimal', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_RUCCombustib', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '20330033313' , PARMT_Descripcion = 'R.U.C. Empresa de Consumo de Combustible Local', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_SetMoneda', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'MND1' , PARMT_Descripcion = 'Moneda por Defecto', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_TDODefault', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'CPD01' , PARMT_Descripcion = 'Tipo de documento de facturacion por defa ', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_TipoRepCot', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = 'A' , PARMT_Descripcion = 'Tipo de Reporte de Cotizacion de Venta', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_TPendiente', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '3' , PARMT_Descripcion = 'Tiempo en que se mostraran la pendientes', PARMT_TipoDato = 'System.Integer', PARMT_General = NULL
    --UNION SELECT PARMT_Id = 'pg_USeriePrin', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Parametro indica si se usara la serie en la impresion', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_USeriePrint', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '1' , PARMT_Descripcion = 'Parametro indica si se usara la serie en la impresion', PARMT_TipoDato = 'Boolean', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_VendedorDefa', APLIC_Codigo = 'TRA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '00000000000' , PARMT_Descripcion = 'Porcentaje I.G.V.', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_VendedorDefa', APLIC_Codigo = 'VTA', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = @SUCUR_Id, PARMT_Valor = '00000000000' , PARMT_Descripcion = 'Vendedor por Defecto', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'pg_Version', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '3.3.1.5' , PARMT_Descripcion = 'Version de la Aplicacion', PARMT_TipoDato = 'String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_VersionLOG', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '0.2.1.0' , PARMT_Descripcion = 'Version del Sistema de Logistica', PARMT_TipoDato = 'System.String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_VersionSAG', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '0.1.0.2' , PARMT_Descripcion = 'Version del Sistema de Administracion General', PARMT_TipoDato = 'System.String', PARMT_General = 1
    UNION SELECT PARMT_Id = 'pg_VersionTRA', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '3.0.0.1' , PARMT_Descripcion = 'Version del Sistema de Transportes', PARMT_TipoDato = 'String', PARMT_General = NULL
    UNION SELECT PARMT_Id = 'PIGV', APLIC_Codigo = '   ', ZONAS_Codigo = @ZONAS_Codigo, SUCUR_Id = 0, PARMT_Valor = '18' , PARMT_Descripcion = 'Porcentaje I.G.V.', PARMT_TipoDato = 'Decimal', PARMT_General = NULL
    ) AS PARA
WHERE NOT PARA.PARMT_Id + '-' + PARA.APLIC_Codigo + '-' + RTRIM(PARA.SUCUR_Id) IN (SELECT PARMT_Id + '-' + APLIC_Codigo + '-' + RTRIM(SUCUR_Id) FROM Parametros)


--SELECT * FROM Parametros

