

SELECT * FROM Logistica.DIST_GuiasRemision WHERE GUIAR_Codigo = '090050000756'
SELECT * FROM Logistica.DIST_GuiasRemisionDetalle WHERE GUIAR_Codigo = '090050000756'

SELECT TOP 100 * FROM Logistica.LOG_Stocks WHERE PERIO_Codigo = '2019' AND GUIAR_Codigo IS NOT NULL
SELECT * FROM TIPOS WHERE TIPOS_Codigo = 'MST01'
SELECT * FROM Logistica.LOG_Stocks WHERE PERIO_Codigo = '2019' AND ALMAC_Id = 1 AND ARTIC_Codigo = '0401029'
SELECT MAX(STOCK_Id)  FROM Logistica.LOG_Stocks WHERE PERIO_Codigo = '2019' AND ALMAC_Id = 1 
SELECT * FROM Logistica.LOG_Stocks WHERE STOCK_Id = 72476
