USE BDNOVACERO
GO

SELECT CODIGO = ARTIC.ARTIC_Codigo
     --, COD_LINEA = RTRIM(ROW_NUMBER()OVER(PARTITION BY LINP.LINEA_Nombre ORDER BY LINP.LINEA_Nombre))
     -- '|' + RTRIM( ROW_NUMBER()OVER(PARTITION BY LINP.LINEA_Nombre, LIN.LINEA_Nombre ORDER BY LINP.LINEA_Nombre, LIN.LINEA_Nombre))
     --, COD_SLINEA = ROW_NUMBER()OVER(PARTITION BY LINP.LINEA_Nombre, LIN.LINEA_Nombre ORDER BY ARTIC.ARTIC_Orden)
     , LINEA = LINP.LINEA_Nombre
     , [SUB-LINEA] = LIN.LINEA_Nombre
     , DESCRIPCION = ARTIC.ARTIC_Descripcion
     , UNIDAD = UND.TIPOS_Descripcion
     , PESO = ARTIC.ARTIC_Peso
     , STOCK = 0.00
          --, ARTIC.*
  FROM dbo.Articulos ARTIC
 INNER JOIN dbo.Lineas LIN ON LIN.LINEA_Codigo = ARTIC.LINEA_Codigo
 INNER JOIN dbo.Lineas LINP ON LINP.LINEA_Codigo = LEFT(ARTIC.LINEA_Codigo, 2)
 INNER JOIN dbo.Tipos UND ON UND.TIPOS_Codigo = ARTIC.TIPOS_CodUnidadMedida
 WHERE ARTIC.ARTIC_Descontinuado = 0
 ORDER BY LINEA, [SUB-LINEA], DESCRIPCION
 --SELECT * FROM dbo.Lineas